### PR TITLE
Changed the font on thickness screen to H2 + arrows

### PR DESCRIPTION
**Pull request by kudresov**

### CODE REVIEW

**Comment by pixeltakeaway** [comment]
The font change is good, but keep the old design of the arrows.

**Review by pixeltakeaway — CHANGES_REQUESTED** [review]
Revert back the arrows

**Comment by kudresov** [comment]
@pixeltakeaway I have arrows **as requested**.

**Review by pixeltakeaway — APPROVED** [review]
All looks good!

**Pull request merged**
